name: 🚀 Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/server/**'
      - 'package.json'
      - 'turbo.json'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🚀 Deploy to Railway
      uses: bervProject/railway-deploy@v1.3.0
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: aicodegen-backend
